

version: "3.9" 

services:
  app:
    build:
      context: ./
    container_name: currency
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_FILE=config.env 
    volumes:
      - ./config.env:/app/config.env:ro 

  postgres:
    image: postgres:15-alpine
    container_name: wallet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "6379:6379"

volumes:
  data-volume:
    driver: local
