basePath: /api/v1
definitions:
  entity.Balance:
    properties:
      EUR:
        type: number
      RUB:
        type: number
      USD:
        type: number
    type: object
  entity.Currency:
    enum:
    - USD
    - RUB
    - EUR
    type: string
    x-enum-varnames:
    - USD
    - RUB
    - EUR
  entity.DepositResponse:
    properties:
      message:
        type: string
      new_balance:
        $ref: '#/definitions/entity.Balance'
    type: object
  entity.ExchangeReq:
    properties:
      amount:
        type: number
      from_currency:
        type: string
      to_currency:
        type: string
    required:
    - amount
    - from_currency
    - to_currency
    type: object
  entity.ExchangeResponse:
    properties:
      exchanged_amount:
        type: number
      message:
        type: string
      new_balance:
        additionalProperties:
          type: number
        type: object
    type: object
  entity.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  entity.RegisterReq:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  entity.Transaction:
    properties:
      amount:
        type: number
      currency:
        $ref: '#/definitions/entity.Currency'
    type: object
host: localhost:8080
info:
  contact: {}
  description: API docs for Wallet-exchanger
  title: Wallet-exchanger
  version: 0.0.1
paths:
  /balance:
    get:
      consumes:
      - application/json
      description: Handler for Getting balance from wallet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Balance'
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      security:
      - ApiKeyAuth: []
      summary: Get balance
      tags:
      - wallet
  /exchange/rates:
    get:
      consumes:
      - application/json
      description: Exchange currency
      parameters:
      - description: FromCurrency, ToCurrency, Amount
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.ExchangeReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.ExchangeResponse'
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      security:
      - ApiKeyAuth: []
      summary: Exchange currency
      tags:
      - exchange
  /login:
    post:
      consumes:
      - application/json
      description: Login user.
      parameters:
      - description: name password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      summary: login
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create user with his wallet.
      parameters:
      - description: name password email
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      summary: register
      tags:
      - auth
  /wallet/deposit:
    post:
      consumes:
      - application/json
      description: Deposit to users wallet
      parameters:
      - description: amount, currency
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.DepositResponse'
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      security:
      - ApiKeyAuth: []
      summary: Deposit
      tags:
      - wallet
  /wallet/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw from users wallet
      parameters:
      - description: amount, currency
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.Transaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.DepositResponse'
        "400":
          description: Bad Request
          schema:
            type: func
        "404":
          description: Not Found
          schema:
            type: func
        "500":
          description: Internal Server Error
          schema:
            type: func
      security:
      - ApiKeyAuth: []
      summary: Withdraw
      tags:
      - wallet
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
